/*
 * 电商对接API参考文档
 * 电商对接API参考文档
 *
 * OpenAPI spec version: 2.2.2
 * Contact: qyang@yicksolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package cn.acey.integrate.usmartbox.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * RemotePutInHistoryResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-11T11:40:26.060Z[GMT]")
public class RemotePutInHistoryResponse extends BasicApiResponse {
  @SerializedName("gridno")
  private String gridno = null;

  @SerializedName("showgridno")
  private String showgridno = null;

  @SerializedName("seqid")
  private String seqid = null;

  @SerializedName("location")
  private String location = null;

  @SerializedName("starttime")
  private String starttime = null;

  @SerializedName("endtime")
  private String endtime = null;

  @SerializedName("status")
  private Integer status = null;

  public RemotePutInHistoryResponse gridno(String gridno) {
    this.gridno = gridno;
    return this;
  }

   /**
   * 完整格号
   * @return gridno
  **/
  @Schema(description = "完整格号")
  public String getGridno() {
    return gridno;
  }

  public void setGridno(String gridno) {
    this.gridno = gridno;
  }

  public RemotePutInHistoryResponse showgridno(String showgridno) {
    this.showgridno = showgridno;
    return this;
  }

   /**
   * 格号，用于显示给客户
   * @return showgridno
  **/
  @Schema(description = "格号，用于显示给客户")
  public String getShowgridno() {
    return showgridno;
  }

  public void setShowgridno(String showgridno) {
    this.showgridno = showgridno;
  }

  public RemotePutInHistoryResponse seqid(String seqid) {
    this.seqid = seqid;
    return this;
  }

   /**
   * 流水号
   * @return seqid
  **/
  @Schema(description = "流水号")
  public String getSeqid() {
    return seqid;
  }

  public void setSeqid(String seqid) {
    this.seqid = seqid;
  }

  public RemotePutInHistoryResponse location(String location) {
    this.location = location;
    return this;
  }

   /**
   * 柜子地址
   * @return location
  **/
  @Schema(description = "柜子地址")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public RemotePutInHistoryResponse starttime(String starttime) {
    this.starttime = starttime;
    return this;
  }

   /**
   * 存入时间
   * @return starttime
  **/
  @Schema(description = "存入时间")
  public String getStarttime() {
    return starttime;
  }

  public void setStarttime(String starttime) {
    this.starttime = starttime;
  }

  public RemotePutInHistoryResponse endtime(String endtime) {
    this.endtime = endtime;
    return this;
  }

   /**
   * 取走时间 (没取的话没这个key)
   * @return endtime
  **/
  @Schema(description = "取走时间 (没取的话没这个key)")
  public String getEndtime() {
    return endtime;
  }

  public void setEndtime(String endtime) {
    this.endtime = endtime;
  }

  public RemotePutInHistoryResponse status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * 1已存入柜子;2用户取走;3快递员取出;4系统复原
   * @return status
  **/
  @Schema(description = "1已存入柜子;2用户取走;3快递员取出;4系统复原")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemotePutInHistoryResponse remotePutInHistoryResponse = (RemotePutInHistoryResponse) o;
    return Objects.equals(this.gridno, remotePutInHistoryResponse.gridno) &&
        Objects.equals(this.showgridno, remotePutInHistoryResponse.showgridno) &&
        Objects.equals(this.seqid, remotePutInHistoryResponse.seqid) &&
        Objects.equals(this.location, remotePutInHistoryResponse.location) &&
        Objects.equals(this.starttime, remotePutInHistoryResponse.starttime) &&
        Objects.equals(this.endtime, remotePutInHistoryResponse.endtime) &&
        Objects.equals(this.status, remotePutInHistoryResponse.status) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gridno, showgridno, seqid, location, starttime, endtime, status, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemotePutInHistoryResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    gridno: ").append(toIndentedString(gridno)).append("\n");
    sb.append("    showgridno: ").append(toIndentedString(showgridno)).append("\n");
    sb.append("    seqid: ").append(toIndentedString(seqid)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    starttime: ").append(toIndentedString(starttime)).append("\n");
    sb.append("    endtime: ").append(toIndentedString(endtime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
