/*
 * 电商对接API参考文档
 * 电商对接API参考文档
 *
 * OpenAPI spec version: 2.2.2
 * Contact: qyang@yicksolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package cn.acey.integrate.usmartbox.client.api;

import cn.acey.integrate.usmartbox.client.ApiException;
import cn.acey.integrate.usmartbox.client.model.BoxSearchResponse;
import cn.acey.integrate.usmartbox.client.model.BranchBoxSearchResponse;
import cn.acey.integrate.usmartbox.client.model.RemotePutInHistoryResponse;
import cn.acey.integrate.usmartbox.client.model.RemotePutInResponse;
import cn.acey.integrate.usmartbox.client.model.RemoteTakeOutResponse;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for BoxApi
 */
@Ignore
public class BoxApiTest {

    private final BoxApi api = new BoxApi();

    /**
     * 远程存
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void remotePutInBoxTest() throws ApiException {
        String apikey = null;
        String nonce = null;
        String sign = null;
        String boxno = null;
        String butype = null;
        String func = null;
        String kphone = null;
        String orderid = null;
        String phone = null;
        String size = null;
        RemotePutInResponse response = api.remotePutInBox(apikey, nonce, sign, boxno, butype, func, kphone, orderid, phone, size);

        // TODO: test validations
    }
    /**
     * 远程存
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void remotePutInBoxHistoryTest() throws ApiException {
        String apikey = null;
        String nonce = null;
        String sign = null;
        String orderid = null;
        RemotePutInHistoryResponse response = api.remotePutInBoxHistory(apikey, nonce, sign, orderid);

        // TODO: test validations
    }
    /**
     * 远程取
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void remoteTakeOutBoxTest() throws ApiException {
        String apikey = null;
        String nonce = null;
        String sign = null;
        String gridno = null;
        String opencode = null;
        String seqid = null;
        RemoteTakeOutResponse response = api.remoteTakeOutBox(apikey, nonce, sign, gridno, opencode, seqid);

        // TODO: test validations
    }
    /**
     * 查询取件状态
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void remoteTakeOutHistoryTest() throws ApiException {
        String apikey = null;
        String nonce = null;
        String sign = null;
        String gridno = null;
        String seqid = null;
        RemoteTakeOutResponse response = api.remoteTakeOutHistory(apikey, nonce, sign, gridno, seqid);

        // TODO: test validations
    }
    /**
     * 根据城市及区号及网点编号查询下属柜子
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchBoxTest() throws ApiException {
        String apikey = null;
        String nonce = null;
        String sign = null;
        String city = null;
        String district = null;
        String branchno = null;
        BoxSearchResponse response = api.searchBox(apikey, nonce, sign, city, district, branchno);

        // TODO: test validations
    }
    /**
     * 根据城市及区号查询下属网点及柜子
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchBranchBoxTest() throws ApiException {
        String apikey = null;
        String nonce = null;
        String sign = null;
        String city = null;
        String district = null;
        BranchBoxSearchResponse response = api.searchBranchBox(apikey, nonce, sign, city, district);

        // TODO: test validations
    }
}
