/*
 * 电商对接API参考文档
 * 电商对接API参考文档
 *
 * OpenAPI spec version: 2.2.2
 * Contact: qyang@yicksolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * Box
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-11T11:22:01.772Z[GMT]")
public class Box {
  @SerializedName("city")
  private String city = null;

  @SerializedName("location")
  private String location = null;

  @SerializedName("boxno")
  private String boxno = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("district")
  private String district = "false";

  @SerializedName("lon")
  private BigDecimal lon = null;

  @SerializedName("lat")
  private BigDecimal lat = null;

  public Box city(String city) {
    this.city = city;
    return this;
  }

   /**
   * 城市代码
   * @return city
  **/
  @Schema(description = "城市代码")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public Box location(String location) {
    this.location = location;
    return this;
  }

   /**
   * 地址
   * @return location
  **/
  @Schema(description = "地址")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public Box boxno(String boxno) {
    this.boxno = boxno;
    return this;
  }

   /**
   * 柜子编号
   * @return boxno
  **/
  @Schema(description = "柜子编号")
  public String getBoxno() {
    return boxno;
  }

  public void setBoxno(String boxno) {
    this.boxno = boxno;
  }

  public Box name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 网点名称
   * @return name
  **/
  @Schema(description = "网点名称")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Box district(String district) {
    this.district = district;
    return this;
  }

   /**
   * Get district
   * @return district
  **/
  @Schema(description = "")
  public String getDistrict() {
    return district;
  }

  public void setDistrict(String district) {
    this.district = district;
  }

  public Box lon(BigDecimal lon) {
    this.lon = lon;
    return this;
  }

   /**
   * Get lon
   * @return lon
  **/
  @Schema(description = "")
  public BigDecimal getLon() {
    return lon;
  }

  public void setLon(BigDecimal lon) {
    this.lon = lon;
  }

  public Box lat(BigDecimal lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Get lat
   * @return lat
  **/
  @Schema(description = "")
  public BigDecimal getLat() {
    return lat;
  }

  public void setLat(BigDecimal lat) {
    this.lat = lat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Box box = (Box) o;
    return Objects.equals(this.city, box.city) &&
        Objects.equals(this.location, box.location) &&
        Objects.equals(this.boxno, box.boxno) &&
        Objects.equals(this.name, box.name) &&
        Objects.equals(this.district, box.district) &&
        Objects.equals(this.lon, box.lon) &&
        Objects.equals(this.lat, box.lat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, location, boxno, name, district, lon, lat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Box {\n");
    
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    boxno: ").append(toIndentedString(boxno)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
