/*
 * 电商对接API参考文档
 * 电商对接API参考文档
 *
 * OpenAPI spec version: 2.2.2
 * Contact: qyang@yicksolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Box;
import io.swagger.client.model.Branch;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * BranchBox
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-11T11:40:26.060Z[GMT]")
public class BranchBox extends Branch {
  @SerializedName("boxlist")
  private List<Box> boxlist = null;

  public BranchBox boxlist(List<Box> boxlist) {
    this.boxlist = boxlist;
    return this;
  }

  public BranchBox addBoxlistItem(Box boxlistItem) {
    if (this.boxlist == null) {
      this.boxlist = new ArrayList<Box>();
    }
    this.boxlist.add(boxlistItem);
    return this;
  }

   /**
   * Get boxlist
   * @return boxlist
  **/
  @Schema(description = "")
  public List<Box> getBoxlist() {
    return boxlist;
  }

  public void setBoxlist(List<Box> boxlist) {
    this.boxlist = boxlist;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BranchBox branchBox = (BranchBox) o;
    return Objects.equals(this.boxlist, branchBox.boxlist) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(boxlist, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BranchBox {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    boxlist: ").append(toIndentedString(boxlist)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
