/*
 * 电商对接API参考文档
 * 电商对接API参考文档
 *
 * OpenAPI spec version: 2.2.2
 * Contact: qyang@yicksolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * Branch
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-11T11:22:01.772Z[GMT]")
public class Branch {
  @SerializedName("city")
  private String city = null;

  @SerializedName("dtname")
  private String dtname = null;

  @SerializedName("branchno")
  private String branchno = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("district")
  private String district = "false";

  @SerializedName("lon")
  private BigDecimal lon = null;

  @SerializedName("lat")
  private BigDecimal lat = null;

  public Branch city(String city) {
    this.city = city;
    return this;
  }

   /**
   * 城市代码
   * @return city
  **/
  @Schema(description = "城市代码")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public Branch dtname(String dtname) {
    this.dtname = dtname;
    return this;
  }

   /**
   * 区
   * @return dtname
  **/
  @Schema(description = "区")
  public String getDtname() {
    return dtname;
  }

  public void setDtname(String dtname) {
    this.dtname = dtname;
  }

  public Branch branchno(String branchno) {
    this.branchno = branchno;
    return this;
  }

   /**
   * 网点编号
   * @return branchno
  **/
  @Schema(description = "网点编号")
  public String getBranchno() {
    return branchno;
  }

  public void setBranchno(String branchno) {
    this.branchno = branchno;
  }

  public Branch name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 网点名称
   * @return name
  **/
  @Schema(description = "网点名称")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Branch district(String district) {
    this.district = district;
    return this;
  }

   /**
   * Get district
   * @return district
  **/
  @Schema(description = "")
  public String getDistrict() {
    return district;
  }

  public void setDistrict(String district) {
    this.district = district;
  }

  public Branch lon(BigDecimal lon) {
    this.lon = lon;
    return this;
  }

   /**
   * Get lon
   * @return lon
  **/
  @Schema(description = "")
  public BigDecimal getLon() {
    return lon;
  }

  public void setLon(BigDecimal lon) {
    this.lon = lon;
  }

  public Branch lat(BigDecimal lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Get lat
   * @return lat
  **/
  @Schema(description = "")
  public BigDecimal getLat() {
    return lat;
  }

  public void setLat(BigDecimal lat) {
    this.lat = lat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Branch branch = (Branch) o;
    return Objects.equals(this.city, branch.city) &&
        Objects.equals(this.dtname, branch.dtname) &&
        Objects.equals(this.branchno, branch.branchno) &&
        Objects.equals(this.name, branch.name) &&
        Objects.equals(this.district, branch.district) &&
        Objects.equals(this.lon, branch.lon) &&
        Objects.equals(this.lat, branch.lat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, dtname, branchno, name, district, lon, lat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Branch {\n");
    
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    dtname: ").append(toIndentedString(dtname)).append("\n");
    sb.append("    branchno: ").append(toIndentedString(branchno)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
