/*
 * 电商对接API参考文档
 * 电商对接API参考文档
 *
 * OpenAPI spec version: 2.2.2
 * Contact: qyang@yicksolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BasicApiResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RemotePutInResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-11T11:40:26.060Z[GMT]")
public class RemotePutInResponse extends BasicApiResponse {
  @SerializedName("gridno")
  private String gridno = null;

  @SerializedName("showgridno")
  private String showgridno = null;

  @SerializedName("opencode")
  private String opencode = null;

  @SerializedName("seqid")
  private String seqid = null;

  public RemotePutInResponse gridno(String gridno) {
    this.gridno = gridno;
    return this;
  }

   /**
   * 打开的格子完整编号
   * @return gridno
  **/
  @Schema(description = "打开的格子完整编号")
  public String getGridno() {
    return gridno;
  }

  public void setGridno(String gridno) {
    this.gridno = gridno;
  }

  public RemotePutInResponse showgridno(String showgridno) {
    this.showgridno = showgridno;
    return this;
  }

   /**
   * 打开的格子编号,用于显示
   * @return showgridno
  **/
  @Schema(description = "打开的格子编号,用于显示")
  public String getShowgridno() {
    return showgridno;
  }

  public void setShowgridno(String showgridno) {
    this.showgridno = showgridno;
  }

  public RemotePutInResponse opencode(String opencode) {
    this.opencode = opencode;
    return this;
  }

   /**
   * 取出密码
   * @return opencode
  **/
  @Schema(description = "取出密码")
  public String getOpencode() {
    return opencode;
  }

  public void setOpencode(String opencode) {
    this.opencode = opencode;
  }

  public RemotePutInResponse seqid(String seqid) {
    this.seqid = seqid;
    return this;
  }

   /**
   * 流水号
   * @return seqid
  **/
  @Schema(description = "流水号")
  public String getSeqid() {
    return seqid;
  }

  public void setSeqid(String seqid) {
    this.seqid = seqid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemotePutInResponse remotePutInResponse = (RemotePutInResponse) o;
    return Objects.equals(this.gridno, remotePutInResponse.gridno) &&
        Objects.equals(this.showgridno, remotePutInResponse.showgridno) &&
        Objects.equals(this.opencode, remotePutInResponse.opencode) &&
        Objects.equals(this.seqid, remotePutInResponse.seqid) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gridno, showgridno, opencode, seqid, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemotePutInResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    gridno: ").append(toIndentedString(gridno)).append("\n");
    sb.append("    showgridno: ").append(toIndentedString(showgridno)).append("\n");
    sb.append("    opencode: ").append(toIndentedString(opencode)).append("\n");
    sb.append("    seqid: ").append(toIndentedString(seqid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
