/*
 * 电商对接API参考文档
 * 电商对接API参考文档
 *
 * OpenAPI spec version: 2.2.2
 * Contact: qyang@yicksolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BasicApiResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RemoteTakeOutResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-11T11:40:26.060Z[GMT]")
public class RemoteTakeOutResponse extends BasicApiResponse {
  @SerializedName("nonce")
  private String nonce = null;

  @SerializedName("showgridno")
  private String showgridno = null;

  public RemoteTakeOutResponse nonce(String nonce) {
    this.nonce = nonce;
    return this;
  }

   /**
   * 随机数 随机数和完整的格号一起可以查询开柜结果
   * @return nonce
  **/
  @Schema(description = "随机数 随机数和完整的格号一起可以查询开柜结果")
  public String getNonce() {
    return nonce;
  }

  public void setNonce(String nonce) {
    this.nonce = nonce;
  }

  public RemoteTakeOutResponse showgridno(String showgridno) {
    this.showgridno = showgridno;
    return this;
  }

   /**
   * 用于显示的格号
   * @return showgridno
  **/
  @Schema(description = "用于显示的格号")
  public String getShowgridno() {
    return showgridno;
  }

  public void setShowgridno(String showgridno) {
    this.showgridno = showgridno;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemoteTakeOutResponse remoteTakeOutResponse = (RemoteTakeOutResponse) o;
    return Objects.equals(this.nonce, remoteTakeOutResponse.nonce) &&
        Objects.equals(this.showgridno, remoteTakeOutResponse.showgridno) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nonce, showgridno, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemoteTakeOutResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    showgridno: ").append(toIndentedString(showgridno)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
