/*
 * 电商对接API参考文档
 * 电商对接API参考文档
 *
 * OpenAPI spec version: 2.2.2
 * Contact: qyang@yicksolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BranchSearchResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BranchApi
 */
@Ignore
public class BranchApiTest {

    private final BranchApi api = new BranchApi();

    /**
     * 根据城市及区号查询下属网点
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchBranchTest() throws ApiException {
        String apikey = null;
        String nonce = null;
        String sign = null;
        String city = null;
        String district = null;
        String orderid = null;
        String phone = null;
        BranchSearchResponse response = api.searchBranch(apikey, nonce, sign, city, district, orderid, phone);

        // TODO: test validations
    }
}
