/*
 * 电商对接API参考文档
 * 电商对接API参考文档
 *
 * OpenAPI spec version: 2.2.2
 * Contact: qyang@yicksolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BasicApiResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrderApi
 */
@Ignore
public class OrderApiTest {

    private final OrderApi api = new OrderApi();

    /**
     * 电商端生成订单后通知智能柜服务器端
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ordercreateTest() throws ApiException {
        String apikey = null;
        String nonce = null;
        String sign = null;
        String orderid = null;
        String phone = null;
        String cardfaceno = null;
        String cardno = null;
        BasicApiResponse response = api.ordercreate(apikey, nonce, sign, orderid, phone, cardfaceno, cardno);

        // TODO: test validations
    }
}
